name: Deploy Streamlit Dashboard

on:
  push:
    branches:
      - main
    paths:
      - 'src/dashboard/**'
      - '.streamlit/**'
      - 'models/explainer_lgbm.pkl'
      - 'models/global_importances.csv'
      - 'data/cleaned/sampled_train_lgbm.csv'  

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest streamlit

      - name: Run dashboard tests
        run: |
          source venv/bin/activate
          pytest src/dashboard/tests_dashboard.py

      # Le déploiement réel vers Streamlit est automatique car l'app est liée au repo.
      # Si un test ne passe pas, le déploiement n'est pas effectué
